 # For details on how this file works refer to:
 #   - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  #  - Check for updates once a week
  #  - Group all updates into a single PR
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: [ "*" ]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/demo/playground/examples"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/demo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/docker-agent"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/docker-test/db"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/elasticsearch"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/extensions/curator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/extensions/enterprise-search"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/extensions/filebeat"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/extensions/fleet"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/extensions/heartbeat"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/extensions/logspout"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/extensions/metricbeat"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/kibana"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/logstash"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/elk-stack/setup"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/multi-demo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/playground"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/demo/playground/examples"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for dev Container
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
      
