 services:
  kanon-postgres:
    image: acapy-test
    ports:
      - "3001:3001"
    command: >
      start
        --label kanon-postgres
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://kanon-postgres:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --genesis-url https://test.bcovrin.vonx.io/genesis
        --wallet-type kanon-anoncreds
        --wallet-name kanon-postgres
        --wallet-key insecure
        --wallet-storage-type postgres_storage
        --wallet-storage-config "{\"url\":\"wallet-db:5432\",\"max_connections\":100,\"min_idle_count\":5,\"max_idle\":10.0,\"max_lifetime\":7200.0}"
        --wallet-storage-creds "{\"account\":\"DB_USER\",\"password\":\"DB_PASSWORD\",\"admin_account\":\"DB_USER\",\"admin_password\":\"DB_PASSWORD\"}"
        --auto-provision
        --log-level debug
        --debug-webhooks
        --notify-revocation
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      tails:
        condition: service_started
      wallet-db:
        condition: service_healthy

  bob:
    image: acapy-test
    ports:
      - "3002:3001"
    command: >
      start
        --label Bob
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://bob:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --genesis-url https://test.bcovrin.vonx.io/genesis
        --wallet-type askar
        --wallet-name bob
        --wallet-key insecure
        --auto-provision
        --log-level info
        --debug-webhooks
        --monitor-revocation-notification
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  example:
    container_name: controller
    build:
      context: ../..
    environment:
      - KANON_POSTGRES=http://kanon-postgres:3001
      - BOB=http://bob:3001
    volumes:
      - ./example.py:/usr/src/app/example.py:ro,z
    command: python -m example
    depends_on:
      kanon-postgres:
        condition: service_healthy
      bob:
        condition: service_healthy

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=https://test.bcovrin.vonx.io/genesis
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO

  wallet-db:
    image: postgres:12
    environment:
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U DB_USER"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s