site_name: Hyperledger Aries ACA-Py Docs
repo_name: hyperledger/aries-cloudagent-python
repo_url: https://github.com/hyperledger/aries-cloudagent-python
theme:
  name: material
  custom_dir: overrides
  logo: https://raw.githubusercontent.com/hyperledger/aries-acapy-docs/main/assets/Hyperledger_Aries_Logo_White.png
  favicon: https://raw.githubusercontent.com/hyperledger/aries-cloudagent-python/main/docs/assets/aries-favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - content.code.copy
  - navigation.expand
  - navigation.footer
  - navigation.instant
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - toc.follow
#  - toc.integrate
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
  - mike
extra:
  version:
    provider: mike
nav:
- Welcome!:
    - Welcome: aca-py.org.md
    - ACA-Py README: README.md
    - Release Notes: CHANGELOG.md
- Features:
    - Developer Introduction: features/DevReadMe.md
    - DevContainer Support: features/devcontainer.md
    - Supported Aries Interop Profiles and RFCs: features/SupportedRFCs.md
    - The Admin API: features/AdminAPI.md
    - ACA-Py Plugins: features/PlugIns.md
    - Multitenant ACA-Py: features/Multitenancy.md
    - Qualified DIDs: features/QualifiedDIDs.md
    - DID Methods: features/DIDMethods.md
    - DID Resolution: features/DIDResolution.md
    - Publishing AnonCreds Objects To Other Ledgers/Verifiable Data Registries: features/AnonCredsMethods.md
    - Configuring Multiple Indy Ledgers: features/Multiledger.md
    - Automatically Endorsing Indy Transations: features/Endorser.md
    - Using W3C JSON-LD Signed Credentials: features/JsonLdCredentials.md
    - Using SD-JWTs: features/SelectiveDisclosureJWTs.md
    - AnonCreds Presentation Validation: features/AnoncredsProofValidation.md
    - Multiple Credential Types: features/Multicredentials.md
    - Code Generation with the Open API: features/UsingOpenAPI.md
    - ACA-Py as a DIDComm Mediator: features/Mediation.md
- Demos:
    - Hyperledger Aries / AnonCreds Workshop: demo/Aries-Workshop.md
    - The Alice-Faber Demo: demo/README.md
    - Open API Tutorial: demo/AriesOpenAPIDemo.md
    - Alice Gets a Phone: demo/AliceGetsAPhone.md
    - Hyperledger Indy Endorser In Action: demo/Endorser.md
    - Using W3C JSON-LD Credentials: demo/AliceWantsAJsonCredential.md
    - DIY -- ACME Controller Workshop: demo/AcmeDemoWorkshop.md
    - Aries Using Postman Demo: demo/AriesPostmanDemo.md
    - Reusing a Connection Between Agents: demo/ReusingAConnection.md
- Getting Started:
    - Becoming an Indy/Aries Developer: gettingStarted/README.md
    - Hyperledger Indy Basics: gettingStarted/IndyBasics.md
    - Hyperledger Aries Basics: gettingStarted/AriesBasics.md
    - Decentralized Identity Demos: gettingStarted/DecentralizedIdentityDemos.md
    - Aries - The Big Picture: gettingStarted/AriesBigPicture.md
    - Aries Architecture: gettingStarted/AriesAgentArchitecture.md
    - Aries Messaging: gettingStarted/AriesMessaging.md
    - Aries Developer Demos: gettingStarted/AriesDeveloperDemos.md
    - Agent Connections: gettingStarted/AgentConnections.md
    - Issuing AnonCreds Credentials: gettingStarted/IssuingAnonCredsCredentials.md
    - Presenting AnonCreds Proofs: gettingStarted/PresentingAnonCredsProofs.md
    - Making Your Own ACA-Py Agent: gettingStarted/YourOwnAriesAgent.md
    - Aries Developer Options: gettingStarted/IndyAriesDevOptions.md
    - DIDComm Messaging: gettingStarted/DIDcommMsgs.md
    - DIDComm Message Routing: gettingStarted/RoutingEncryption.md
    - DIDComm Message Routing Example: gettingStarted/AriesRoutingExample.md
    - TODO Connecting to an Indy Network: gettingStarted/ConnectIndyNetwork.md
    - AnonCreds Credential Revocation: gettingStarted/CredentialRevocation.md
- Deploying:
    - Deployment Model: deploying/deploymentModel.md
    - Upgrading ACA-Py: deploying/UpgradingACA-Py.md
    - Indy SDK to Askar Migration: deploying/IndySDKtoAskarMigration.md
    - Controller Migration to use AnonCreds Rust: deploying/AnoncredsControllerMigration.md
    - The Use of Poetry in ACA-Py: deploying/Poetry.md
    - ACA-Py Container Images: deploying/ContainerImagesAndGithubActions.md
    - Databases: deploying/Databases.md
    - Persistent Queues and Caching: deploying/RedisPlugins.md
    - The askar-anoncreds Wallet Type: deploying/AnonCredsWalletType.md
- Testing/Troubleshooting:
    - Running and Creating Unit Tests: testing/UnitTests.md
    - Managing Logging: testing/Logging.md
    - ACA-Py Integration Tests: testing/INTEGRATION-TESTS.md
    - Protocol Tracing: testing/AgentTracing.md
    - Troubleshooting: testing/Troubleshooting.md
- Contributing:
    - How to Contribute: CONTRIBUTING.md
    - Maintainers: MAINTAINERS.md
    - Hyperledger Code of Conduct: CODE_OF_CONDUCT.md
    - Security Vulnerability Reporting: SECURITY.md
    - Publishing an ACA-Py Release: PUBLISHING.md
    - Updating the ACA-Py ReadTheDocs Site: UpdateRTD.md
