version: "3"
services:
  issuer-agent:
    image: issuer-agent
    environment:
      - WALLET_TYPE=${WALLET_TYPE}
      - POSTGRESQL_WALLET_HOST=${POSTGRESQL_WALLET_HOST}
      - POSTGRESQL_WALLET_PORT=${POSTGRESQL_WALLET_PORT}
      - POSTGRESQL_WALLET_USER=${POSTGRESQL_USER}
      - POSTGRESQL_WALLET_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_WALLET_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
      - WALLET_ENCRYPTION_KEY=${WALLET_ENCRYPTION_KEY}
      - INDY_WALLET_SEED=${INDY_WALLET_SEED}
      - INDY_WALLET_DID=${INDY_WALLET_DID}
      # - WEBHOOK_URL=http://tob-api:${AGENT_WEBHOOK_PORT}/callback
      - HTTP_INTERFACE_PORT=${HTTP_INTERFACE_PORT}
      - WS_INTERFACE_PORT=${WS_INTERFACE_PORT}
      - AGENT_ADMIN_PORT=${AGENT_ADMIN_PORT}
      - AGENT_NAME=${AGENT_NAME}
    networks:
      - issuer
    ports:
      - ${HTTP_INTERFACE_PORT}:${HTTP_INTERFACE_PORT}
      - ${WS_INTERFACE_PORT}:${WS_INTERFACE_PORT}
      - ${AGENT_ADMIN_PORT}:${AGENT_ADMIN_PORT}
    depends_on:
      - wallet-db
    entrypoint: /bin/bash
    command: [
        "-c",
        "icatagent \
        --inbound-transport http '0.0.0.0' ${HTTP_INTERFACE_PORT} \
        --inbound-transport ws '0.0.0.0' ${WS_INTERFACE_PORT} \
        --endpoint ${AGENT_ENDPOINT} \
        --outbound-transport ws \
        --outbound-transport http \
        --genesis-transactions genesis \
        --auto-respond-messages \
        --accept-invites \
        --accept-requests \
        --auto-ping-connection \
        --wallet-type 'indy' \
        --wallet-name 'icat_agent_wallet' \
        --wallet-key '${WALLET_ENCRYPTION_KEY}' \
        --storage-type '${WALLET_TYPE}' \
        --storage-config '{\"url\":\"${POSTGRESQL_WALLET_HOST}:${POSTGRESQL_WALLET_PORT}\",\"max_connections\":5}' \
        --storage-creds '{\"account\":\"${POSTGRESQL_USER}\",\"password\":\"${POSTGRESQL_PASSWORD}\",\"admin_account\":\"postgres\",\"admin_password\":\"${POSTGRESQL_ADMIN_PASSWORD}\"}' \
        --seed '${INDY_WALLET_SEED}' \
        --admin '0.0.0.0' ${AGENT_ADMIN_PORT} \
        --label ${AGENT_NAME} \
        --log-level debug \
        --protocol indy_catalyst_issuer_registration",
      ]

  #
  # wallet-db
  #
  wallet-db:
    image: postgresql
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    networks:
      - issuer
    ports:
      - 5434:5432
    volumes:
      - issuer-wallet-db:/var/lib/pgsql/data
    #command:
    #  postgres -c 'log_statement=all' -c 'logging_collector=on' -c 'log_destination=stderr'

networks:
  issuer:

volumes:
  issuer-wallet-db:
