version: 2
jobs:
  agent-build:
    docker:
      - image: bcgovimages/von-image:py36-1.8-0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-pip-dependencies-{{ .Branch }}-{{ checksum "agent/requirements.txt" }}-{{ checksum "agent/requirements.dev.txt" }}
            - v2-pip-dependencies-{{ .Branch }}-
      - run:
          name: Install Python Dependencies
          command: |
            cd agent
            python3 -m venv venv
            . venv/bin/activate
            pip install \
              -r requirements.txt \
              -r requirements.dev.txt \
              pytest

      - save_cache:
          paths:
            - agent/venv
          key: v2-pip-dependencies-{{ .Branch }}-{{ checksum "agent/requirements.txt" }}-{{ checksum "agent/requirements.dev.txt" }}

      - run:
          name: Run Agent Tests
          command: |
            mkdir test-reports
            mkdir test-reports/pytest
            cd agent
            . venv/bin/activate
            pytest

      - run:
          name: Push to Codecov.io
          command: |
              bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports


  django-build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - tob_api-pip-dependencies-{{ .Branch }}-{{ checksum "starter-kits/credential-registry/server/tob-api/requirements.txt" }}
            - tob_api-pip-dependencies-{{ .Branch }}-

      - run:
          name: Install Python Dependencies
          command: |
            cd ./starter-kits/credential-registry/server/tob-api
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt \
              codecov \
              coverage
            pip install \
              -e ../../../../credential-registry/server/django-icat-api/ \
              -e ../../../../credential-registry/server/python-indy-api/

      - save_cache:
          paths:
            - starter-kits/credential-registry/server/tob-api/venv
          key: tob_api-pip-dependencies-{{ .Branch }}-{{ checksum "starter-kits/credential-registry/server/tob-api/requirements.txt" }}

      - run:
          name: Run Django Tests and submit results to Codecov.io
          command: |
            mkdir test-reports
            mkdir test-reports/unittest
            cd ./starter-kits/credential-registry/server/tob-api
            . venv/bin/activate
            coverage run --source='.' manage.py test
            codecov

      # - run:
      #     name: Push to Codecov.io
      #     command: |
      #         codecov

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
 version: 2
 indy_catalyst:
   jobs:
     - agent-build
     - django-build