# Sample docker-compose to start a local aca-py in multi-ledger mode
# To start aca-py and the postgres database, just run `docker-compose up`
# To shut down the services run `docker-compose rm` - this will retain the postgres database, so you can change aca-py startup parameters
# and restart the docker containers without losing your wallet data
# If you want to delete your wallet data just run `docker volume ls -q | xargs docker volume rm`

# Note this requires von-network (https://github.com/bcgov/von-network) and indy-tails-server (https://github.com/bcgov/indy-tails-server) are already running

version: "3"
services:
  vcr-agent:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.run
    ports:
      - 8010:8010
      - 8001:8001
    depends_on:
      - wallet-db
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 5; \
        aca-py start \
        --auto-provision \
        --seed '00000000o_faber_secondary_school' \
        --inbound-transport http '0.0.0.0' 8001 \
        --endpoint 'http://host.docker.internal:8001' \
        --outbound-transport http \
        --genesis-url 'https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_builder_genesis' \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-messages \
        --auto-respond-credential-proposal \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --auto-verify-presentation \
        --tails-server-base-url 'https://tails-test.vonx.io' \
        --notify-revocation \
        --monitor-revocation-notification \
        --wallet-type 'askar' \
        --wallet-name 'acapy_agent_wallet' \
        --wallet-key 'key' \
        --wallet-storage-type 'postgres_storage' \
        --wallet-storage-config '{\"url\":\"wallet-db:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"DB_USER\",\"password\":\"DB_PASSWORD\",\"admin_account\":\"DB_USER\",\"admin_password\":\"DB_PASSWORD\"}' \
        --admin '0.0.0.0' 8010 \
        --admin-insecure-mode \
        --label 'tester_agent' \
        --log-level 'info' ",
      ]
    volumes:
      - ./ledgers.yaml:/home/indy/ledgers.yaml
    networks:
      - tails-network

# note - if you want to start aca-py in single-ledger mode, replace the `--genesis-transactions-list` parameter above with:
#        --genesis-url 'https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_builder_genesis' \
#        --genesis-url 'http://host.docker.internal:9000/genesis' \
#        --genesis-transactions-list 'ledgers.yaml' \

  wallet-db:
    image: postgres:12
    environment:
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
    ports:
      - 5433:5432
    volumes:
      - wallet-db-data:/var/lib/pgsql/data
    networks:
      - tails-network

volumes:
  wallet-db-data:

networks:
  tails-network:
    external:
      name: docker_tails-server
