# General
label: Mediator
endpoint: http://localhost:3002
inbound-transport:
  - [http, 0.0.0.0, 3002]
outbound-transport: http
no-ledger: true

# Admin
admin: [0.0.0.0, 3003]
admin-insecure-mode: true

# Connections
debug-connections: true
connections-invite: true
invite-multi-use: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true

# Mediation
open-mediation: true
auto-send-keylist-update-in-requests: true
auto-send-keylist-update-in-create-invitation: true
# Webhooks
# webhook-url: http://localhost:1080/mediator
