 services:
  alice:
    image: acapy-test
    ports:
      - "3001:3001"
    environment:
      RUST_LOG: warn
    command: >
      start
        --label Alice
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://alice:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --no-ledger
        --wallet-type askar
        --wallet-name alice
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  bob:
    image: acapy-test
    ports:
      - "3002:3001"
    environment:
      RUST_LOG: warn
    command: >
      start
        --label Bob
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://bob:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --no-ledger
        --wallet-type askar
        --wallet-name bob
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --monitor-revocation-notification
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  mediator:
    image: acapy-test
    ports:
      - "3003:3001"
    environment:
      RUST_LOG: warn
    command: >
      start
        --label Mediator
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://mediator:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --no-ledger
        --wallet-type askar
        --wallet-name mediator
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --enable-undelivered-queue
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  example:
    container_name: controller
    build:
      context: ../..
    environment:
      - ALICE=http://alice:3001
      - BOB=http://bob:3001
      - MEDIATOR=http://mediator:3001
    volumes:
      - ./example.py:/usr/src/app/example.py:ro,z
    command: python -m example
    depends_on:
      alice:
        condition: service_healthy
      bob:
        condition: service_healthy
      mediator:
        condition: service_healthy
