name: BDD Interop Integration Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    # Run on openwallet-foundation and non-draft PRs or on non-PR events
    if: (github.repository == 'openwallet-foundation/acapy') && ((github.event_name == 'pull_request' && github.event.pull_request.draft == false) || (github.event_name != 'pull_request'))
    outputs:
      is_release: ${{ steps.check_if_release.outputs.is_release }}
    steps:
      - name: checkout-acapy
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check changed files
        id: check-changed-files
        uses: tj-actions/changed-files@v45.0.9
        with:
          files_yaml: |
            src: 
              - acapy_agent/**/*
              - poetry.lock
              - pyproject.toml
              - docker/*
      - name: Check if src files changed
        id: check-if-src-changed
        run: |
          if [ "${{ steps.check-changed-files.outputs.src_any_changed }}" != "true" ] && [ '${{ github.event_name }}' == 'pull_request' ]; then
            echo "No src files changed..."
            echo run_tests=false >> $GITHUB_OUTPUT
          fi
      - name: Check if PR is a release
        if: steps.check-if-src-changed.outputs.run_tests != 'false'
        uses: ./.github/actions/is-release
        id: check_if_release
      - name: Request GitHub API for PR data
        if: steps.check-if-src-changed.outputs.run_tests != 'false'
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: get_pr_data
        with:
          route: GET /repos/${{ github.event.repository.full_name }}/pulls/${{ github.event.number }}
      - name: Prepare Interop Tests
        if: (steps.check-if-src-changed.outputs.run_tests != 'false' || steps.check_if_release.outputs.is_release == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        run: |
          # Get AATH 
          git clone https://github.com/openwallet-foundation/owl-agent-test-harness.git

          # Change fork and branch for pull requests
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            echo ${{ fromJson(steps.get_pr_data.outputs.data).head.repo.html_url }}
            echo ${{ fromJson(steps.get_pr_data.outputs.data).head.ref }}
            sed -i 's|@git+https://github.com/openwallet-foundation/acapy@main|@git+${{ fromJson(steps.get_pr_data.outputs.data).head.repo.html_url }}@${{ fromJson(steps.get_pr_data.outputs.data).head.ref }}|g' ./owl-agent-test-harness/aries-backchannels/acapy/requirements-main.txt
          fi
          cat owl-agent-test-harness/aries-backchannels/acapy/requirements-main.txt

          cd owl-agent-test-harness
          ./manage build -a acapy-main
      - name: Run PR Interop Tests Indy
        if: (steps.check_if_release.outputs.is_release != 'true' && github.event_name == 'pull_request' && steps.check-if-src-changed.outputs.run_tests != 'false')
        run: |
          cd owl-agent-test-harness
          NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @critical -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Anoncreds >> output.txt
      - name: Run Release or Nightly Interop Tests Indy
        if: (steps.check_if_release.outputs.is_release == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && steps.check-if-src-changed.outputs.run_tests != 'false')
        run: |
          cd owl-agent-test-harness
          NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @critical -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Anoncreds >> output.txt
      - name: Run Release or Nightly Interop Tests Anoncreds
        if: (steps.check_if_release.outputs.is_release == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && steps.check-if-src-changed.outputs.run_tests != 'false')
        run: |
          cd owl-agent-test-harness
          BACKCHANNEL_EXTRA_acapy_main="{\"wallet-type\":\"askar-anoncreds\"}" NO_TTY=1 LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-main -t @AcceptanceTest -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Indy -t ~@CredFormat_Indy >> output.txt
      - name: Check If Tests Failed
        if: steps.check-if-src-changed.outputs.run_tests != 'false'
        run: |
          cd owl-agent-test-harness
          cat output.txt
          if grep "Failing scenarios:" output.txt; then
              echo "Tests failed"
              exit 1
          else
              echo "Tests passed"
              exit 0
          fi

