name: Nightly Build
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  NAME: aries-cloudagent-python
  PYTHON_VERSION: 3.7

jobs:
  nightly:
    name: Nightly
    runs-on: ubuntu-latest
    steps:
      - name: Gather image info
        id: info
        run: |
          echo "::set-output name=repo-owner::${GITHUB_REPOSITORY_OWNER,,}"

      - name: Check image exists
        id: image-exists
        uses: dbluhm/image-tag-exists@257851f02e3473a75719e26b5a566ea5457da4ef
        with:
          tag: ghcr.io/${{ steps.info.outputs.repo-owner }}/${{ env.NAME }}:py${{ env.PYTHON_VERSION }}-nightly-${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        if: steps.image-exists.outputs.exists != 'true'

      - name: Cache Docker layers
        if: steps.image-exists.outputs.exists != 'true'
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        if: steps.image-exists.outputs.exists != 'true'
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container Registry
        if: steps.image-exists.outputs.exists != 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Base Image Metadata
        if: steps.image-exists.outputs.exists != 'true'
        id: base-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/${{ env.NAME }}
          tags: |
            type=raw,value=py${{ env.PYTHON_VERSION }}-nightly
            type=sha,format=long,prefix=py${{ env.PYTHON_VERSION }}-nightly-

      - name: Build and Push Base Image to ghcr.io
        if: steps.image-exists.outputs.exists != 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: ${{ steps.base-meta.outputs.tags }}
          labels: ${{ steps.base-meta.outputs.labels }}
          build-args: |
            python_version=${{ env.PYTHON_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        if: steps.image-exists.outputs.exists != 'true'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache-base
