name: PR Tests

on:
  pull_request:

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
    with:
      python-version: "3.9"
      os: "ubuntu-latest"

  tests-indy:
    name: Tests (Indy)
    uses: ./.github/workflows/tests-indy.yml
    with:
      python-version: "3.9"
      indy-version: "1.16.0"
      os: "ubuntu-latest"
