name: Tests (Indy)
on:
  pull_request:

env:
  INDY_VERSION: 1.16.0

jobs:
  info:
    name: Gather image info
    runs-on: ubuntu-latest
    outputs:
      repo-owner: ${{ steps.info.outputs.owner-lc }}
      indy-version: ${{ steps.info.outputs.indy-version }}
      indy-sdk-url: ${{ steps.info.outputs.indy-sdk-url }}
      base-dep-hash: ${{ steps.info.outputs.base-hash }}
      test-dep-hash: ${{ steps.info.outputs.test-hash }}
    steps:
      - uses: actions/checkout@v3
      - name: Gather image info
        id: info
        run: |
          echo "::set-output name=owner-lc::${GITHUB_REPOSITORY_OWNER,,}"
          echo "::set-output name=indy-version::${{env.INDY_VERSION}}"
          echo "::set-output name=indy-sdk-url::https://codeload.github.com/hyperledger/indy-sdk/tar.gz/refs/tags/v${{ env.INDY_VERSION }}"
          echo "::set-output name=base-hash::${{ hashFiles('docker/Dockerfile.indy-base') }}"
          echo "::set-output name=test-hash::${{ hashFiles('requirements*.txt', 'docker/Dockerfile.test-indy') }}"

  base-image:
    name: Publish base image
    needs: info
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Check image exists
        id: image-exists
        uses: dbluhm/image-tag-exists@257851f02e3473a75719e26b5a566ea5457da4ef
        with:
          tag: ghcr.io/${{ needs.info.outputs.repo-owner }}/indy-python-test:py${{ matrix.python-version }}-${{ env.INDY_VERSION }}-${{ needs.info.outputs.base-dep-hash }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        if: steps.image-exists.outputs.exists != 'true'

      - name: Cache Docker layers
        if: steps.image-exists.outputs.exists != 'true'
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-base
          key: ${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-

      - name: Set up Docker Buildx
        if: steps.image-exists.outputs.exists != 'true'
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container Registry
        if: steps.image-exists.outputs.exists != 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Base Image Metadata
        if: steps.image-exists.outputs.exists != 'true'
        id: base-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ needs.info.outputs.repo-owner }}/indy-python-test
          tags: |
            type=raw,value=py${{ matrix.python-version }}-${{ env.INDY_VERSION }}-${{ needs.info.outputs.base-dep-hash }}

      - name: Build and Push Base Image to ghcr.io
        if: steps.image-exists.outputs.exists != 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: docker/Dockerfile.indy-base
          tags: ${{ steps.base-meta.outputs.tags }}
          labels: ${{ steps.base-meta.outputs.labels }}
          build-args: |
            python_version=${{ matrix.python-version }}
            indy_version=${{ needs.info.outputs.indy_version }}
            indy_sdk_url=${{ needs.info.outputs.indy-sdk-url }}
          cache-from: type=local,src=/tmp/.buildx-cache-base
          cache-to: type=local,dest=/tmp/.buildx-cache-base-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        if: steps.image-exists.outputs.exists != 'true'
        run: |
          rm -rf /tmp/.buildx-cache-base
          mv /tmp/.buildx-cache-base-new /tmp/.buildx-cache-base


  test-image:
    name: Publish test image
    needs: ["info", "base-image"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:

      - name: Check image exists
        id: image-exists
        uses: dbluhm/image-tag-exists@257851f02e3473a75719e26b5a566ea5457da4ef
        with:
          tag: ghcr.io/${{ needs.info.outputs.repo-owner }}/acapy-test:py${{ matrix.python-version }}-${{ needs.info.outputs.indy-version }}-${{ needs.info.outputs.test-dep-hash }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        if: steps.image-exists.outputs.exists != 'true'

      - name: Cache Docker layers
        if: steps.image-exists.outputs.exists != 'true'
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-test
          key: ${{ runner.os }}-buildx-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-test-

      - name: Set up Docker Buildx
        if: steps.image-exists.outputs.exists != 'true'
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container Registry
        if: steps.image-exists.outputs.exists != 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Test Image Metadata
        if: steps.image-exists.outputs.exists != 'true'
        id: test-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ needs.info.outputs.repo-owner }}/acapy-test
          tags: |
            type=raw,value=py${{ matrix.python-version }}-${{ env.INDY_VERSION }}-${{ needs.info.outputs.test-dep-hash }}

      - name: Build and Push Test Image to ghcr.io
        if: steps.image-exists.outputs.exists != 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: docker/Dockerfile.test-indy
          tags: ${{ steps.test-meta.outputs.tags }}
          labels: ${{ steps.test-meta.outputs.labels }}
          build-args: |
            base_image=ghcr.io/${{ needs.info.outputs.repo-owner }}/indy-python-test:py${{ matrix.python-version }}-${{ needs.info.outputs.indy-version }}-${{ needs.info.outputs.base-dep-hash }}
          cache-from: type=local,src=/tmp/.buildx-cache-test
          cache-to: type=local,dest=/tmp/.buildx-cache-test-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        if: steps.image-exists.outputs.exists != 'true'
        run: |
          rm -rf /tmp/.buildx-cache-test
          mv /tmp/.buildx-cache-test-new /tmp/.buildx-cache-test

  tests:
    name: Tests (Indy)
    needs:
      - info
      - base-image
      - test-image
    runs-on: ubuntu-latest
    container: ghcr.io/${{ needs.info.outputs.repo-owner }}/acapy-test:py${{ matrix.python-version }}-${{ needs.info.outputs.indy-version }}-${{ needs.info.outputs.test-dep-hash }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Run pytest
        run: |
          pytest
